pip install numpy
pip install pandas
pip install csv
pip install json
pip install pysqlite3 
pip install pandas.io.sql
pip install matplotlib
pip install itertools
pip install plotly
pip install seaborn
pip install xgboost
pip install sklearnoide